version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  Applicationstart:
    - location: scripts/start_server.sh
      runas: root
