version: 0.0
os: linux
files:
  - source: /
    destination: /opt/deployment/
hooks:
  AfterInstall:
    - location: scripts/serviceApp.bash
      runas: root
  ApplicationStart:
    - location: scripts/startApp.bash
      runas: root
 ApplicationAfterStart:
    - location: scripts/afterstartApp.bash
      runas: root
  ApplicationStop:
    - location: scripts/stopApp.bash
      runas: root
  ValidateService:
    - location: scripts/verifyApp.bash
      runas: root
