version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html/
  - source: appspec.yml
    destination: /home/ec2-user
 hooks:
   ApplicationStop:
     - location: scripts/stop_server.sh
       timeout: 300
       runas: ec2-user
