version: 0.0
os: linux
files:
  - source: index.php
    destination: /var/www/html/
  - source: appspec.yml
    destination: /home/ec2-user
 hooks:
 BeforeInstall:
  - location: scripts/install_dependencies.sh
       timeout: 300
       runas: ec2-user
  - location: scripts/start_server.sh
       timeout: 300
       runas: ec2-user
 ApplicationStop:
     - location: scripts/stop_server.sh
       timeout: 300
       runas: ec2-user
