version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/html/
  - source: /logout.php
    destination: /var/www/html/
hooks:
  Applicationstart:
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
